-- Banter/lines.lua
-- All line pools (gender-neutral, short, punchy). Add more over time freely.

Banter = Banter or {}

Banter.LinePools = {
    ATTACK = {
        "Take that, %t!",
        "You picked the wrong fight!",
        "Down you go!",
        "Let's end this!",
        "Stay down!",
        "Try harder!",
        "Not impressed!",
        "Out of my way!",
        "That all you've got?",
        "You're done!",
        "Big mistake!",
        "I warned you!",
        "How do you like that, %t?",
        "You want some more?",
        "Taste my wrath!",
        "Feel my fury!",
        "Die, %t!"
    },

    INTERRUPT = {
        "Nope!",
        "Not happening!",
        "Interrupted!",
        "Shut it down!",
        "Denied!",
        "Cut that out!",
        "Nice try!",
        "Silence!",
        "Not today!",
        "Stopped!",
        "Try again!",
        "Absolutely not!",
        "No, you don't!",
        "Think again!"
    },

    DEFENSIVE = {
        "Hold the line!",
        "Not breaking!",
        "I'm still standing!",
        "You'll have to do better!",
        "Brace!",
        "Dig in!",
        "Still here!",
        "That won't be enough!",
        "Standing firm!",
        "Endure!",
        "I can take it!",
        "Not done yet!",
        "You won't take me down!",
        "Bring it!"
    },

    BURST = {
        "Alright, let's go!",
        "Now!",
        "This ends now!",
        "Full force!",
        "No more games!",
        "Time to finish it!",
        "Here we go!",
        "Everything I've got!",
        "Let's make this count!",
        "All in!",
        "Enough!",
        "Push!",
        "Let's turn things up a notch!",
        "Time to die, %t!",
        "Go, go, go!"
    },

    -- Context pools for the Speak button:
    COMBAT = {
        "Focus up!",
        "Eyes sharp!",
        "Stay ready!",
        "We're in it now!",
        "Careful!",
        "Keep moving!",
        "Don't get sloppy!",
        "Watch it!",
        "Stay alert!",
        "This isn't over!",
        "Press the advantage!",
        "Steady!",
    },

    LOWHP = {
        "That hurt!",
        "Not good!",
        "I'm in trouble!",
        "Could use a hand!",
        "This is bad!",
        "I'm hit!",
        "Getting weak…",
        "Careful—real careful.",
        "Still fighting!",
        "I can't take many more!",
        "This is close!",
        "Barely holding!",
    },

    VICTORY = {
        "That's done!",
        "Good enough!",
        "It's over!",
        "Stay down!",
        "Handled!",
        "Next!",
        "Finally!",
        "That went well.",
        "Could've been worse.",
        "Clear!",
        "Moving on.",
        "Not bad!",
        "Woohoo!",
        "Yes!",
        "Piece of cake!",
        "Well fought!",
        "That'll do!"
    },

    IDLE_GENERIC = {
        "Okay, what now?",
        "This is an interesting place.",
        "My feet hurt.",
        "Let's take a breather.",
        "I need to keep busy.",
        "I'd like to revisit {randomplace} sometime.",
        "What was I doing again?",
        "I need to clean my armor.",
        "Something smells, and it's not me.",
        "No time to dawdle",
        "Anyone seen my knife?",
        "That's curious.",
        "Ooh, look at that!",
        "Why does this remind me of {randomplace}?",
        "I wonder if I can find a nice place to eat in {randomplace}.",
        "Ugh, what did I just step in?",
        "I need to remember to get this stitched up later.",
        "I think that street urchin just stole my purse!",
        "Why are there so many rats in this place?",
        "My allergies are acting up again.",

        "@EMOTE:SIGH",
        "@EMOTE:STRETCH",
        "@EMOTE:YAWN",
        "@EMOTE:SHRUG",
        "@EMOTE:LOOK",
        "@EMOTE:COUGH",
        "@EMOTE:SNEEZE",
        "@EMOTE:SNIFF",

        -- Alliance flavor
        "[ALLIANCE] Did you see the herd of Tauren grazing outside of {randomplace}?",
        "[ALLIANCE] You can always tell Horde territory by the smell.",
        "[ALLIANCE] Stormwind may be loud, but at least it's civilized.",
        "[ALLIANCE] Watch your back around here. Horde spies have been known to lurk about.",
        "[ALLIANCE] I hear the Horde has been making trouble near {randomplace}.",
        "[ALLIANCE] The Horde thinks they can just take what they want.",
        "[ALLIANCE] Some forsaken left a maggot on the barstool at the tavern. Disgusting.",
        "[ALLIANCE] I wish orcs bathed more often.",
        "[ALLIANCE] Horde and table manners—never the two shall meet.",
        "[ALLIANCE] Did you hear the one about the goblin and the wash cloth? Yeah, me neither.",

        -- Horde flavor
        "[HORDE] Alliance scouts never last long around {randomplace}.",
        "[HORDE] The Alliance calls this land \"theirs\". Cute.",
        "[HORDE] If an Alliance patrol shows up, things will get interesting.",
        "[HORDE] An Alliance patrol near {randomplace}? Must be lost.",
        "[HORDE] The Alliance builds walls. We build warriors.",
        "[HORDE] The Alliance loves rules. Shame rules don't win battles.",
        "[HORDE] Humans talk big for folk who panic when things stop being polite.",
        "[HORDE] The Alliance says we lack discipline. We just don't ask permission.",
        "[HORDE] The Horde doesn't need approval. We need purpose.",
    },

    IDLE_PLACE = {
        "{zone} has a way of pulling you in.",
        "Something about {zone} feels different today.",
        "I could get used to {subzone}.",
        "{subzone} never really feels quiet.",
        "Hard not to stare around {subzone}.",
        "I could get lost in {subzone}.",
        "You can learn a lot just listening in {subzone}.",
        "{zone} always has a story.",
        "{zone} feels {vibe} right now.",
        "{city} is {vibe} today.",
        "{city} doesn't slow down, does it?",
        "The air in {zone} feels… {vibe}.",
        "{subzone} has its own kind of trouble.",
        "I should stay sharp in {subzone}.",
        "Feels like {zone} is watching.",
        "I've got a good feeling about {zone}.",
        "I've got a bad feeling about {zone}.",
        "This part of {zone}… it sticks with you.",
        "How many times have I been to {subzone} now?",
        "I could disappear into {city} and no one would notice."
    },

    IDLE_TARGET_PLAYER_FRIENDLY = {
        "{target} looks like {theyve} seen some things.",
        "You doing alright, {target}?",
        "Something tells me {target} knows what {they}'re doing.",
        "{target} carries {themself} like a veteran.",
        "If {target} says run, I'm running.",
        "{target} seems steady. I like that.",
        "I'd rather have {target} with us than against us.",
        "{target} has that 'been there' look.",
        "If you need a hand, {target}, say the word.",
        "I'll take {target} over most company.",
        "Nice to see you, {target}.",
        "Nice weapon, {target}!",
        "Looking good, {target}!",
        "Hey, {target}. Have you ever been to {randomplace}?",
        "{target}, know any good places to eat in {randomplace}?",
        "Hey, {target}, has your helmet ever chafed your eybrows?",
        "@EMOTE:POKE",
        "@EMOTE:EYE",
        "@EMOTE:HIGHFIVE",
        "@EMOTE:NOD",
        "@EMOTE:SMILE",
        "@EMOTE:PONDER",
        "@EMOTE:WAVE"

    },

    IDLE_TARGET_PLAYER_HOSTILE = {
        "{target}… yeah, I don't trust {them}.",
        "Keep your distance, {target}.",
        "{target} looks like trouble on purpose.",
        "If {target} moves, I move.",
        "I've got my eye on you, {target}.",
        "{target} is itching for a mistake.",
        "Don't start something, {target}.",
        "This one feels personal already: {target}.",
        "{target} is watching us. Let {them}.",
        "I'm not looking for a fight… but {target} might be.",
        "{target}'s got those beady eyes.",
        "@EMOTE:GLARE",
        "@EMOTE:SCOWL",
        "@EMOTE:STARE",
        "@EMOTE:FROWN",
        "@EMOTE:PONDER"
    },

    IDLE_TARGET_NPC_FRIENDLY = {
        "{target} looks busy.",
        "I won't get in your way, {target}.",
        "{target} seems like {theyve} got a job to do.",
        "If {target} is calm, I'm calm.",
        "Best not to cause trouble around {target}.",
        "{target} looks like {theyve} had a long day.",
        "Not every fight needs starting, {target}.",
        "I'll behave. Mostly.",
        "Seems safe enough here… for now.",
        "{target} doesn't look amused.",
        "@EMOTE:SMILE",
        "@EMOTE:NOD",
        "@EMOTE:WAVE",
    },

    IDLE_TARGET_NPC_HOSTILE = {
        "{target} is sizing me up.",
        "That's a bad look, {target}.",
        "If {target} twitches, we're in trouble.",
        "I don't like the way {target} is standing there.",
        "{target} is thinking about it. I can tell.",
        "Easy… easy…",
        "We're not friends, {target}.",
        "{target} is waiting for an opening.",
        "{target} is going to be a problem.",
        "Yeah… no. Not today, {target}.",
        "@EMOTE:GLARE",
        "@EMOTE:SCOWL",
        "@EMOTE:STARE",
        "@EMOTE:FROWN",
    },

    HEAL = {
        "Hold still. I've got you.",
        "You're not done yet.",
        "Not today.",
        "I can fix that.",
        "You'll live.",
        "Easy… easy…",
        "Stay with me.",
        "I said you're not dying.",
        "That's better.",
        "I've seen worse.",
        "You're fine. Mostly.",
        "Try not to do that again.",
        "Breathe.",
        "I've got you covered.",
        "You owe me one.",
        "Don't make this harder than it needs to be.",
        "I can only do so much.",
        "You're welcome.",
        "Back on your feet.",
        "Next time, duck.",
    }
}
